# Python for Data — Pandas Basics (Week 1, Day 5)

## Exploratory Data Analysis using a Real Dataset

In [1]:
import pandas as pd

In [6]:
df = pd.read_csv('Downloads/archive/tech_mental_health_burnout.csv')

In [8]:
print("Dataset loaded successfully")
df.head()

Dataset loaded successfully

,age,gender,job_role,experience_years,company_size,work_mode,work_hours_per_week,overtime_hours,meetings_per_day,deadlines_missed,...,screen_time_hours,caffeine_intake,social_support_score,has_therapy,stress_level,anxiety_score,depression_score,burnout_score,burnout_level,seeks_professional_help
0,50,Female,Backend Developer,7.8,Large,Hybrid,45.0,0.0,5.0,0,...,8.6,1,4.4,0,4.8,4.3,2.6,1.0,Low,0
1,36,Male,Frontend Developer,1.8,Mid-size,Remote,56.0,4.0,6.0,0,...,11.5,4,4.1,0,6.7,4.8,4.6,3.7,Moderate,0
2,29,Male,DevOps,2.5,MNC,Hybrid,43.0,2.0,6.0,3,...,6.8,3,6.5,0,4.5,4.0,2.5,1.0,Low,0
3,42,Female,Backend Developer,1.5,Mid-size,Hybrid,57.0,9.0,4.0,1,...,10.2,5,2.5,0,6.1,5.8,1.8,3.6,Moderate,0
4,40,Female,Frontend Developer,3.4,Large,Remote,49.0,0.0,3.0,4,...,11.9,5,4.6,0,7.2,5.9,2.4,3.5,Low,0

In [13]:
df.shape

(150000, 25)

In [14]:
print("\nDataset information:")
df.info()

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 25 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   age                      150000 non-null  int64
 1   gender                   150000 non-null  object
 2   job_role                 150000 non-null  object
 3   experience_years         150000 non-null  float64
 4   company_size             150000 non-null  object
 5   work_mode                150000 non-null  object
 6   work_hours_per_week      150000 non-null  float64
 7   overtime_hours           150000 non-null  float64
 8   meetings_per_day         150000 non-null  float64
 9   deadlines_missed         150000 non-null  int64
 10  job_satisfaction         150000 non-null  float64
 11  manager_support          150000 non-null  float64
 12  work_life_balance        150000 non-null  float64
 13  sleep_hours              150000 non-null  float64
 14  physical_activity_days   150000 non-null  int64
 15  screen_time_hours        150000 non-null  float64
 16  caffeine_intake          150000 non-null  int64
 17  social_support_score     150000 non-null  float64
 18  has_therapy              150000 non-null  int64
 19  stress_level             150000 non-null  float64
 20  anxiety_score            150000 non-null  float64
 21  depression_score         150000 non-null  float64
 22  burnout_score            150000 non-null  float64
 23  burnout_level            150000 non-null  object
 24  seeks_professional_help  150000 non-null  int64
dtypes: float64(14), int64(6), object(5)
memory usage: 28.6+ MB

In [16]:
print("\nStatistical summary:")
df.describe()

Statistical summary:

,age,experience_years,work_hours_per_week,overtime_hours,meetings_per_day,deadlines_missed,job_satisfaction,manager_support,work_life_balance,sleep_hours,physical_activity_days,screen_time_hours,caffeine_intake,social_support_score,has_therapy,stress_level,anxiety_score,depression_score,burnout_score,seeks_professional_help
count,150000.000000,150000.000000,150000.00000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000
mean,38.025340,5.055010,47.00758,6.127180,4.010893,1.284193,5.500248,5.497537,5.016357,6.499120,2.599833,8.002713,2.101693,5.498163,0.251133,5.785428,4.523763,3.096687,2.114121,0.096333
std,9.510609,2.878602,7.89331,3.783618,1.978316,1.426264,1.956102,1.956915,1.948553,1.192343,1.814880,1.987813,1.300247,1.957432,0.433667,1.331506,1.201506,1.187668,1.112614,0.295049
min,22.000000,0.000000,30.00000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,3.000000,0.000000,3.000000,0.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000
25%,30.000000,3.000000,42.00000,3.000000,3.000000,0.000000,4.200000,4.100000,3.700000,5.700000,1.000000,6.700000,1.000000,4.200000,0.000000,4.900000,3.700000,2.200000,1.000000,0.000000
50%,38.000000,5.000000,47.00000,6.000000,4.000000,1.000000,5.500000,5.500000,5.000000,6.500000,2.000000,8.000000,2.000000,5.500000,0.000000,5.800000,4.500000,3.100000,1.900000,0.000000
75%,46.000000,7.000000,52.00000,9.000000,5.000000,2.000000,6.900000,6.800000,6.400000,7.300000,4.000000,9.300000,3.000000,6.800000,1.000000,6.700000,5.300000,3.900000,2.800000,0.000000
max,54.000000,18.500000,84.00000,24.000000,12.000000,5.000000,10.000000,10.000000,10.000000,10.000000,7.000000,16.000000,5.000000,10.000000,1.000000,10.000000,9.600000,8.100000,8.100000,1.000000

In [18]:
# 3. Count categorical values

print("\nPassenger count by gender:")
print(df["gender"].value_counts())

Passenger count by gender:
gender
Male          82286
Female        60281
Non-binary     7433
Name: count, dtype: int64

In [25]:
print("\nEmployees by Job Role:")
df["job_role"].value_counts()

Employees by Job Role:

job_role
Software Engineer     37623
Data Scientist        22442
ML Engineer           18153
Backend Developer     18079
Frontend Developer    17967
DevOps                14897
Product Manager       11925
QA Engineer            8914
Name: count, dtype: int64

In [26]:
print("\nBurnout Level Distribution:")
df["burnout_level"].value_counts()

Burnout Level Distribution:

burnout_level
Low         131620
Moderate     18315
High            65
Name: count, dtype: int64

In [27]:
# 4. Select columns
print("\nSelected Columns:")
df[["age", "gender", "job_role", "stress_level", "burnout_level"]].head()

Selected Columns:

   age  gender            job_role  stress_level burnout_level
0   50  Female   Backend Developer           4.8           Low
1   36    Male  Frontend Developer           6.7      Moderate
2   29    Male              DevOps           4.5           Low
3   42  Female   Backend Developer           6.1      Moderate
4   40  Female  Frontend Developer           7.2           Low

In [30]:
# Filter employees with high burnout scores
print("\nEmployees with Burnout Score Above 2:")
df[df["burnout_score"] > 2.0].head()

Employees with Burnout Score Above 2:

,age,gender,job_role,experience_years,company_size,work_mode,work_hours_per_week,overtime_hours,meetings_per_day,deadlines_missed,...,screen_time_hours,caffeine_intake,social_support_score,has_therapy,stress_level,anxiety_score,depression_score,burnout_score,burnout_level,seeks_professional_help
1,36,Male,Frontend Developer,1.8,Mid-size,Remote,56.0,4.0,6.0,0,...,11.5,4,4.1,0,6.7,4.8,4.6,3.7,Moderate,0
3,42,Female,Backend Developer,1.5,Mid-size,Hybrid,57.0,9.0,4.0,1,...,10.2,5,2.5,0,6.1,5.8,1.8,3.6,Moderate,0
4,40,Female,Frontend Developer,3.4,Large,Remote,49.0,0.0,3.0,4,...,11.9,5,4.6,0,7.2,5.9,2.4,3.5,Low,0
6,32,Female,Frontend Developer,1.6,MNC,Hybrid,54.0,3.0,6.0,0,...,9.7,3,4.8,1,7.3,6.3,1.8,4.5,Moderate,1
8,45,Female,Product Manager,6.5,Startup,Remote,55.0,9.0,1.0,2,...,8.4,1,3.6,1,6.4,5.4,4.1,3.0,Low,0

In [31]:
# Filter employees working more than 40 hours per week
print("\nEmployees Working More Than 40 Hours:")
df[df["work_hours_per_week"] > 40].head()

Employees Working More Than 40 Hours:

,age,gender,job_role,experience_years,company_size,work_mode,work_hours_per_week,overtime_hours,meetings_per_day,deadlines_missed,...,screen_time_hours,caffeine_intake,social_support_score,has_therapy,stress_level,anxiety_score,depression_score,burnout_score,burnout_level,seeks_professional_help
0,50,Female,Backend Developer,7.8,Large,Hybrid,45.0,0.0,5.0,0,...,8.6,1,4.4,0,4.8,4.3,2.6,1.0,Low,0
1,36,Male,Frontend Developer,1.8,Mid-size,Remote,56.0,4.0,6.0,0,...,11.5,4,4.1,0,6.7,4.8,4.6,3.7,Moderate,0
2,29,Male,DevOps,2.5,MNC,Hybrid,43.0,2.0,6.0,3,...,6.8,3,6.5,0,4.5,4.0,2.5,1.0,Low,0
3,42,Female,Backend Developer,1.5,Mid-size,Hybrid,57.0,9.0,4.0,1,...,10.2,5,2.5,0,6.1,5.8,1.8,3.6,Moderate,0
4,40,Female,Frontend Developer,3.4,Large,Remote,49.0,0.0,3.0,4,...,11.9,5,4.6,0,7.2,5.9,2.4,3.5,Low,0

In [33]:
# 5. Handle missing values
print("\nMissing Values Before Cleaning:")
df.isnull().sum()

Missing Values Before Cleaning:

age                        0
gender                     0
job_role                   0
experience_years           0
company_size               0
work_mode                  0
work_hours_per_week        0
overtime_hours             0
meetings_per_day           0
deadlines_missed           0
job_satisfaction           0
manager_support            0
work_life_balance          0
sleep_hours                0
physical_activity_days     0
screen_time_hours          0
caffeine_intake            0
social_support_score       0
has_therapy                0
stress_level               0
anxiety_score              0
depression_score           0
burnout_score              0
burnout_level              0
seeks_professional_help    0
dtype: int64

In [42]:
# Fill missing numerical values with their column median
for col in df.select_dtypes(include="number").columns:
    df[col] = df[col].fillna(df[col].median())

In [43]:
# Fill missing categorical values with their mode
for col in df.select_dtypes(include="object").columns:
    if df[col].isnull().any():
        df[col] = df[col].fillna(df[col].mode()[0])

In [44]:
print("\nMissing Values After Cleaning:")
print(df.isnull().sum())

Missing Values After Cleaning:
age                        0
gender                     0
job_role                   0
experience_years           0
company_size               0
work_mode                  0
work_hours_per_week        0
overtime_hours             0
meetings_per_day           0
deadlines_missed           0
job_satisfaction           0
manager_support            0
work_life_balance          0
sleep_hours                0
physical_activity_days     0
screen_time_hours          0
caffeine_intake            0
social_support_score       0
has_therapy                0
stress_level               0
anxiety_score              0
depression_score           0
burnout_score              0
burnout_level              0
seeks_professional_help    0
dtype: int64

In [36]:
# 6. Group by job role and aggregate
print("\nAverage Stress and Burnout by Job Role:")
df.groupby("job_role").agg(
        Employee_Count=("age", "count"),
        Average_Stress=("stress_level", "mean"),
        Average_Burnout=("burnout_score", "mean"),
        Average_Sleep=("sleep_hours", "mean")
    ).round(2)

Average Stress and Burnout by Job Role:

,Employee_Count,Average_Stress,Average_Burnout,Average_Sleep
job_role,,,,
Backend Developer,18079,5.78,2.11,6.49
Data Scientist,22442,5.80,2.13,6.50
DevOps,14897,5.78,2.12,6.50
Frontend Developer,17967,5.80,2.13,6.49
ML Engineer,18153,5.77,2.11,6.51
Product Manager,11925,5.79,2.11,6.51
QA Engineer,8914,5.77,2.10,6.49
Software Engineer,37623,5.79,2.11,6.51

In [37]:
# Group by work mode
print("\nAverage Burnout by Work Mode:")
print(
    df.groupby("work_mode")["burnout_score"]
    .mean()
    .round(2)
)

Average Burnout by Work Mode:
work_mode
Hybrid    2.11
Onsite    2.12
Remote    2.11
Name: burnout_score, dtype: float64

In [39]:
# 7. Demonstrate loc and iloc
print("\nUsing loc:")
print(df.loc[0, ["age", "gender", "job_role"]])

print("\nUsing iloc:")
df.iloc[0:5, 0:5]

Using loc:
age                        50
gender                 Female
job_role    Backend Developer
Name: 0, dtype: object

Using iloc:

   age  gender            job_role  experience_years company_size
0   50  Female   Backend Developer               7.8        Large
1   36    Male  Frontend Developer               1.8     Mid-size
2   29    Male              DevOps               2.5          MNC
3   42  Female   Backend Developer               1.5     Mid-size
4   40  Female  Frontend Developer               3.4        Large

In [41]:
# 8. Export cleaned data
df.to_csv("cleaned_employee_burnout.csv", index=False)

print("\nCleaned dataset exported successfully!")

Cleaned dataset exported successfully!